### PR TITLE
Some updates around subscriptions

### PR DESCRIPTION
**Pull request by donnguyen**
Hi folks,

Just some small updates around Subscription that I think will be helpful for some others as well.

Cheers

### CODE REVIEW

**Comment by alexmamonchik** [comment]
@donnguyen please, rebase `init-v4` branch and run tests. Then we'll merge this PR and prepare a release with newest gems and Stripe API versions

**Comment by donnguyen** [comment]
@alexmamonchik sorry for the late reply. The PR is now up-to-date. Cheers

**Review by alexmamonchik — APPROVED** [review]

**Comment by alexmamonchik** [comment]
> @alexmamonchik sorry for the late reply. The PR is now up-to-date. Cheers

Thank you for your help with it. What do you think about tests for your code? Are existing tests cover it?

**Comment by donnguyen** [comment]
@alexmamonchik the existing tests cover it. Thanks

**Comment by donnguyen** [comment]
hi @alexmamonchik, not sure if we need any more test for these changes?

**Pull request merged**
