### PR TITLE
Update all webhook fixtures with the latest version from the Stripe API

### PR DESCRIPTION
**Pull request by rbclark**
This utilizes a tool I setup to log all of the current requests from the stripe API using the `stripe trigger` CLI command: https://github.com/rbclark/stripe-webhook-logger. This should provide much more up to date mock data for users attempting to test webhooks.

### CODE REVIEW

**Comment by sbansal** [comment]
Can we get this PR merged please?

**Comment by rbclark** [comment]
@sbansal In the meantime if you add these JSON files in `spec/fixtures/stripe_webhooks`, they will be picked up by the `StripeMock`. I'd definitely like to see this merged as well, just figured I'd give you a temporary alternative.

https://github.com/stripe-ruby-mock/stripe-ruby-mock#customizing-webhooks

**Comment by rbclark** [comment]
@sbansal Fully agree, unfortunately it seems so far I’ve failed to get any of the maintainers interest or attention.

**Comment by TastyPi** [comment]
Could you include the tool in the PR so that we can easily update these in the future?

**Review by TastyPi — APPROVED** [review]

**Pull request merged**
