### PR TITLE
Introduce ideal and sepa_debit types for PaymentMethod

### PR DESCRIPTION
**Pull request by mnin**

### CODE REVIEW

**Comment by klaustopher** [comment]
Maybe as an inspiration: The way we implemented it in our local fork: https://github.com/dbdrive/stripe-ruby-mock/commit/1cd0c8f3a8f9fb1a8de5396de04beb756d2bfde1

**Comment by SeTeM** [comment]
What's left to merge this one?

**Comment by alexmamonchik** [comment]
@SeTeM nothing. done

**Comment by mnin** [comment]
nice, thanks!

**Pull request merged**
