### PR TITLE
Fix ruby 2.7 deprecation warnings

### LINKED ISSUE #725: Ruby 2.7 deprecation warning
Relevant stack/libraries:
stripe-ruby-mock - 3.0.1
Rails - 6.0.3.1
Ruby - 2.7.1

Running my test suite since upgrading to Ruby 2.7 yields the following warning message:
lib/stripe_mock/api/instance.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

### PR DESCRIPTION
**Pull request by coding-chimp**
Hey, this is fixing all the ruby 2.7 deprecation warnings I could find while running tests in a work project and the tests of this project.

It should fix #725.

### CODE REVIEW

**Comment by rakibulislam** [comment]
@alexmamonchik Can we please get this merged and released? Thank you.

**Comment by zokioki** [comment]
Ruby 3.0 has been [released today](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/) so these deprecations are now in effect for v3, bump for getting this merged 🙏

**Comment by FireFart** [comment]
@alexmamonchik any chance to get this merged as this gem is currently broken with ruby-3.0.0?

**Comment by csalvato** [comment]
@alexmamonchik @gilbert Another +1 to get thismerged in.

**Review by csalvato — APPROVED** [review]
LGTM 👍🏼

**Comment by FireFart** [comment]
@csalvato thanks for merging this! Any plan when a new version of this gem will be released?

**Comment by csalvato** [comment]
@FireFart I am trying to resolve some issues with the tests (being handled with another user contributed PR), then plan to create a new release candidate and push that as a gem update.  In the meantime, you can reference the current commit hash on `master` in your `Gemfile`, if you need this urgently.

**Pull request merged**
