### PR TITLE
Add allowed params to subscriptions

### PR DESCRIPTION
**Pull request by dominikdarnel**
Add :off_session, :trial_from_plan, and :expand params to allowed params in subscription

### CODE REVIEW

**Comment by lpsBetty** [comment]
Can we merge this?

**Comment by csalvato** [comment]
@gilbert I'd like to merge this and a few other PRs and create a release. I've not done this before. What's the process for creating a new release of the gem?

**Comment by lpsBetty** [comment]
@csalvato I have read this [issue's comment](https://github.com/stripe-ruby-mock/stripe-ruby-mock/issues/763#issuecomment-777141584), have you got a collaborator invite to this repo?

**Comment by csalvato** [comment]
@ips

> @csalvato I have read this [issue's comment](https://github.com/stripe-ruby-mock/stripe-ruby-mock/issues/763#issuecomment-777141584), have you got a collaborator invite to this repo?

@lpsBetty Yes, I have. But a bit gunshy on merging since there are no tests, and I don't know how to create a release just yet.

**Comment by lpsBetty** [comment]
@csalvato 

About the new release:

Maybe this gem can help you create a new release: https://github.com/svenfuchs/gem-release#gem-release 

What the current authors did was creating a release branch, and then tag the merge commit: 
https://github.com/stripe-ruby-mock/stripe-ruby-mock/commit/0e167a63ec0bb6ad0c197fa4fd32c3e8046b71c7
https://github.com/stripe-ruby-mock/stripe-ruby-mock/releases/tag/v3.0.1

**Pull request merged**
