### PR TITLE
support on price api

### PR DESCRIPTION
**Pull request by hidenba**
The implementation maintains minimal compatibility with the planAPI

### CODE REVIEW

**Comment by pbeckinger** [comment]
Thanks for the PR. I think https://github.com/stripe-ruby-mock/stripe-ruby-mock/blob/master/lib/stripe_mock/request_handlers/helpers/subscription_helpers.rb#L114 also needs to be updated since price object doesnt use `amount`.

**Comment by jamesprior** [comment]
> Thanks for the PR. I think https://github.com/stripe-ruby-mock/stripe-ruby-mock/blob/master/lib/stripe_mock/request_handlers/helpers/subscription_helpers.rb#L114 also needs to be updated since price object doesnt use `amount`.

Would it be as straightforward as something like?
```ruby
items.each do |item| 
  quantity = item[:quantity] || 1
  amount = item[:price].present? ? item[:price][:unit_amount]: item[:plan][:amount]
  total += quantity * amount
end
```

I'd love to see this get merged in.

**Comment by Asdolo** [comment]
So what's the state of this issue?

**Comment by csalvato** [comment]
I just spent a few hours writing a patch for this, but then found that @hidenba has written it already!

Happy to see it here, and hopefully this can get merged in.

What will it take to get either this or #758 merged in?  @gilbert have you abandoned the project?  It's cool if you have, but maybe we need to make a community fork, if that's the case.

**Pull request merged**
